// packages/app/src/pages/Play.svelte
<script lang="ts">
  import { push } from 'svelte-spa-router';
  import { onMount } from 'svelte';
  import { FocusElement, focusElement, playerName } from '../stores';
  import { Key } from '../configs/keycodes.config';
  import Chat from '../components/chat/Chat.svelte';
  import Game from '../components/game/Game.svelte';

  if (!String($playerName).length) {
    push('#/');
  }

  onMount(() => {
    document.body.style.overflow = 'hidden';
    function focusChatOnEnter(e: KeyboardEvent): void {
      if (e.key === Key.Enter && $focusElement !== FocusElement.Chat) {
        $focusElement = FocusElement.Chat;
      }
    }

    window.addEventListener('keyup', focusChatOnEnter);

    return () => {
      window.removeEventListener('keyup', focusChatOnEnter);
      document.body.style.overflow = 'initial';
    };
  });
</script>

<div class="Play">
  <Chat />
  <Game />
</div>

<style>
  .Play {
    width: 100%;
    height: 100%;
  }
</style>

// packages/app-react/src/components/pages/Play/index.tsx
import React, { useEffect } from 'react';
import { Redirect } from 'react-router-dom';
import { routes } from '../../../configs/routes.config';
import { FocusStore, PlayerStore } from '../../../stores';
import { Chat } from '../../chat';
import styles from './Play.module.scss';
import { Game } from '../../game';
import { Key } from '../../../configs/keycodes.config';
import { FocusElement } from '../../../types';

const Play: React.FC = () => {
  const player = PlayerStore.useStoreState((state) => state);
  const focusElement = FocusStore.useStoreState((state) => state.focusElement);
  const setFocusElement = FocusStore.useStoreActions(
    (actions) => actions.setFocusElement,
  );

  useEffect(() => {
    document.body.style.overflow = 'hidden';
  }, [document]);

  useEffect(() => {
    const focusChatOnEnter = (e: KeyboardEvent) => {
      if (e.key === Key.Enter && focusElement !== FocusElement.Chat) {
        setFocusElement(FocusElement.Chat);
      }
    };

    window.addEventListener('keyup', focusChatOnEnter);

    return () => {
      window.removeEventListener('keyup', focusChatOnEnter);
    };
  }, [window, focusElement, setFocusElement]);

  if (!String(player.name).length) {
    return <Redirect to={routes.home.path} />;
  }

  return (
    <div className={styles.play}>
      <Chat playerName={player.name} />
      <Game playerName={player.name} />
    </div>
  );
};

export default Play;
