// packages/app-react/src/components/game/Player/index.tsx
import React, { EffectCallback, useCallback, useEffect, useState } from 'react';
import * as BABYLON from '@babylonjs/core';
import { PlayerDTO } from '@reapers/game-client';

enum AnimationKey {
  Defeat = 0,
  Idle = 1,
  Pickup = 2,
  Punch = 3,
  ReceiveHit = 4,
  Shoot = 5,
  SitDown = 6,
  StandUp = 7,
  Victory = 8,
  Walk = 9,
  WalkCarry = 10,
}

type PlayerProps = {
  camera?: BABYLON.FollowCamera;
  player: PlayerDTO;
  scene: BABYLON.Scene | undefined;
  frameIndex: number;
};

const Player: React.FC<PlayerProps> = (props) => {
  const [assets, setAssets] = useState<BABYLON.AssetContainer>();
  const [currentAnimation, setCurrentAnimation] = useState<BABYLON.AnimationGroup>();
  const loadAssets = useCallback((): void => {
    if (props.scene) {
      BABYLON.SceneLoader.LoadAssetContainerAsync(
        '/models/',
        'characters/player.glb',
      ).then((result) => {
        result.meshes[0].scaling = new BABYLON.Vector3(0.3, 0.3, -0.3);
        result.meshes[0].rotate(BABYLON.Axis.Y, Math.PI, BABYLON.Space.WORLD);
        result.animationGroups[AnimationKey.Walk].speedRatio = 2;

        for (let i = 0; i < result.animationGroups.length; i++) {
          result.animationGroups[i].reset().stop();
        }

        result.addAllToScene();
        setAssets(result);
      });
    }
  }, [props.scene]);
  useEffect(loadAssets, [loadAssets]);

  const switchAnimation = useCallback(
    (animationKey: AnimationKey): void => {
      if (assets?.animationGroups) {
        const newAnimation = assets.animationGroups[animationKey];

        if (currentAnimation !== newAnimation) {
          currentAnimation?.stop();
          setCurrentAnimation(newAnimation);
          newAnimation?.play(true);
        }
      }
    },
    [currentAnimation, setCurrentAnimation, assets?.animationGroups],
  );

  const updatePlayer = useCallback((): void => {
    if (props.camera) {
      if (assets?.meshes[0] && props.player) {
        assets.meshes[0].position = new BABYLON.Vector3(...props.player.position);
        assets.meshes[0].rotation = new BABYLON.Vector3(...props.player.rotation);

        if (props.player.moveDirection) {
          switchAnimation(AnimationKey.Walk);
        } else {
          switchAnimation(AnimationKey.Idle);
        }
      }
    }
  }, [props.frameIndex]);
  useEffect(updatePlayer, [updatePlayer]);

  const attachCamera = useCallback(() => {
    if (props.camera && assets?.meshes[0]) {
      props.camera.lockedTarget = assets?.meshes[0];
    }
  }, [props.camera, assets?.meshes]);
  useEffect(attachCamera, [attachCamera]);

  const disposeAssetsOnUnmount = useCallback(
    (): ReturnType<EffectCallback> => (): void => {
      assets?.dispose();
    },
    [assets],
  );
  useEffect(disposeAssetsOnUnmount, [disposeAssetsOnUnmount]);

  return null;
};

export default Player;

// packages/app/src/components/Player/Player.svelte
<script>
  import * as BABYLON from '@babylonjs/core';
  import { MoveDirection, PlayerDTO } from '@reapers/game-client';
  import { onDestroy } from 'svelte';
  import { AnimationKey } from './player.utils';

  export let player: PlayerDTO = new PlayerDTO();
  export let scene: BABYLON.Scene | undefined;
  export let camera: BABYLON.FollowCamera | undefined = undefined;

  let assets: BABYLON.AssetContainer | undefined;
  let mainMesh: BABYLON.AbstractMesh | undefined;
  let currentAnimation: BABYLON.AnimationGroup | undefined;

  function loadAssets() {
    BABYLON.SceneLoader.LoadAssetContainerAsync('/models/', 'characters/player.glb').then(
      (result) => {
        assets = result;
        mainMesh = assets.meshes[0];
        mainMesh.scaling = new BABYLON.Vector3(0.3, 0.3, -0.3);
        mainMesh.rotate(BABYLON.Axis.Y, Math.PI, BABYLON.Space.WORLD);
        assets.animationGroups[AnimationKey.Walk].speedRatio = 2;

        for (let i = 0; i < assets.animationGroups.length; i++) {
          assets.animationGroups[i].reset().stop();
        }

        assets.addAllToScene();
      },
    );
  }

  function switchAnimation(animationKey: AnimationKey) {
    console.log('animationKey', animationKey);
    const newAnimation = assets?.animationGroups[animationKey];

    if (newAnimation && newAnimation !== currentAnimation) {
      currentAnimation?.stop();
      currentAnimation = newAnimation;
      currentAnimation.play(true);
    }
  }

  function updatePlayerPosition(x = 0, y = 0, z = 0) {
    console.log('updatePlayerPosition');
    if (mainMesh) {
      mainMesh.position = new BABYLON.Vector3(x, y, z);
    }
  }

  function updatePlayerRotation(x = 0, y = 0, z = 0) {
    console.log('updatePlayerRotation');
    if (mainMesh) {
      mainMesh.rotation = new BABYLON.Vector3(x, y, z);
    }
  }

  function updatePlayerMoveDirection(direction: MoveDirection) {
    console.log('updatePlayerMoveDirection');
    if (mainMesh && direction) {
      switchAnimation(AnimationKey.Walk);
    } else {
      switchAnimation(AnimationKey.Idle);
    }
  }

  $: {
    if (scene) {
      loadAssets();
    }
  }

  $: mainMeshId = mainMesh?.id;

  $: {
    if (camera && mainMesh) {
      camera.lockedTarget = mainMesh;
    }
  }

  $: position = player.position;
  $: [posX, posY, posZ] = position;
  $: {
    if (mainMeshId) {
      updatePlayerPosition(posX, posY, posZ);
    }
  }

  $: rotation = player.rotation;
  $: [rotX, rotY, rotZ] = rotation;
  $: {
    if (mainMeshId) {
      updatePlayerRotation(rotX, rotY, rotZ);
    }
  }

  $: moveDirection = player.moveDirection;
  $: {
    if (mainMeshId) {
      updatePlayerMoveDirection(moveDirection);
    }
  }

  onDestroy(() => {
    console.log('disposing assets');
    assets?.dispose();
  });
</script>

<style>
</style>
