// packages/app/src/components/Player/Player.svelte
<script>
  import * as BABYLON from '@babylonjs/core';
  import { MoveDirection, PlayerDTO } from '@reapers/game-client';
  import { onDestroy } from 'svelte';
  import { AnimationKey } from './player.utils';

  export let player: PlayerDTO = new PlayerDTO();
  export let scene: BABYLON.Scene | undefined;
  export let camera: BABYLON.FollowCamera | undefined = undefined;

  let assets: BABYLON.AssetContainer | undefined;
  let mainMesh: BABYLON.AbstractMesh | undefined;
  let currentAnimation: BABYLON.AnimationGroup | undefined;

  function loadAssets() {
    BABYLON.SceneLoader.LoadAssetContainerAsync('/models/', 'characters/player.glb').then(
      (result) => {
        assets = result;
        mainMesh = assets.meshes[0];
        mainMesh.scaling = new BABYLON.Vector3(0.3, 0.3, -0.3);
        mainMesh.rotate(BABYLON.Axis.Y, Math.PI, BABYLON.Space.WORLD);
        assets.animationGroups[AnimationKey.Walk].speedRatio = 2;

        for (let i = 0; i < assets.animationGroups.length; i++) {
          assets.animationGroups[i].reset().stop();
        }

        assets.addAllToScene();
      },
    );
  }

  function switchAnimation(animationKey: AnimationKey) {
    console.log('animationKey', animationKey);
    const newAnimation = assets?.animationGroups[animationKey];

    if (newAnimation && newAnimation !== currentAnimation) {
      currentAnimation?.stop();
      currentAnimation = newAnimation;
      currentAnimation.play(true);
    }
  }

  function updatePlayerPosition(x = 0, y = 0, z = 0) {
    console.log('updatePlayerPosition');
    if (mainMesh) {
      mainMesh.position = new BABYLON.Vector3(x, y, z);
    }
  }

  function updatePlayerRotation(x = 0, y = 0, z = 0) {
    console.log('updatePlayerRotation');
    if (mainMesh) {
      mainMesh.rotation = new BABYLON.Vector3(x, y, z);
    }
  }

  function updatePlayerMoveDirection(direction: MoveDirection) {
    console.log('updatePlayerMoveDirection');
    if (mainMesh && direction) {
      switchAnimation(AnimationKey.Walk);
    } else {
      switchAnimation(AnimationKey.Idle);
    }
  }

  $: {
    if (scene) {
      loadAssets();
    }
  }

  $: mainMeshId = mainMesh?.id;

  $: {
    if (camera && mainMesh) {
      camera.lockedTarget = mainMesh;
    }
  }

  $: position = player.position;
  $: [posX, posY, posZ] = position;
  $: {
    if (mainMeshId) {
      updatePlayerPosition(posX, posY, posZ);
    }
  }

  $: rotation = player.rotation;
  $: [rotX, rotY, rotZ] = rotation;
  $: {
    if (mainMeshId) {
      updatePlayerRotation(rotX, rotY, rotZ);
    }
  }

  $: moveDirection = player.moveDirection;
  $: {
    if (mainMeshId) {
      updatePlayerMoveDirection(moveDirection);
    }
  }

  onDestroy(() => {
    console.log('disposing assets');
    assets?.dispose();
  });
</script>

<style>
</style>

// packages/app/src/components/game/Player/index.tsx
import React, { useCallback, useEffect, useState } from 'react';
import * as BABYLON from '@babylonjs/core';
import { MoveDirection, PlayerDTO, RotationDirection } from '@reapers/game-client';
import { Key } from '../../../configs/keycodes.config';

enum AnimationKey {
  Defeat = 0,
  Idle = 1,
  Pickup = 2,
  Punch = 3,
  ReceiveHit = 4,
  Shoot = 5,
  SitDown = 6,
  StandUp = 7,
  Victory = 8,
  Walk = 9,
  WalkCarry = 10,
}

const isRotationDirection = (value: string): boolean => {
  return ([Key.d, Key.q] as string[]).indexOf(value) != -1;
};

const isMoveDirection = (value: string): boolean => {
  return ([Key.z, Key.s, Key.a, Key.e] as string[]).indexOf(value) != -1;
};

type PlayerProps = {
  scene: BABYLON.Scene | undefined;
  camera: BABYLON.FollowCamera | undefined;
  player: PlayerDTO;
  updateMoveDirection: (direction: MoveDirection) => void;
  updateRotationDirection: (direction: RotationDirection) => void;
};

const Player: React.FC<PlayerProps> = (props) => {
  const [meshes, setMeshes] = useState<BABYLON.AbstractMesh[]>([]);
  const [animations, setAnimations] = useState<
    Record<AnimationKey, BABYLON.AnimationGroup>
  >();
  const [currentAnimation, setCurrentAnimation] = useState<BABYLON.AnimationGroup>();

  useEffect(() => {
    if (props.scene) {
      BABYLON.SceneLoader.LoadAssetContainerAsync(
        '/models/',
        'characters/player.glb',
      ).then((result) => {
        result.meshes[0].scaling = new BABYLON.Vector3(0.3, 0.3, -0.3);
        result.meshes[0].rotate(BABYLON.Axis.Y, Math.PI, BABYLON.Space.WORLD);
        result.animationGroups[AnimationKey.Walk].speedRatio = 2;
        setAnimations({
          [AnimationKey.Defeat]: result.animationGroups[AnimationKey.Defeat],
          [AnimationKey.Idle]: result.animationGroups[AnimationKey.Idle],
          [AnimationKey.Pickup]: result.animationGroups[AnimationKey.Pickup],
          [AnimationKey.Punch]: result.animationGroups[AnimationKey.Punch],
          [AnimationKey.ReceiveHit]: result.animationGroups[AnimationKey.ReceiveHit],
          [AnimationKey.Shoot]: result.animationGroups[AnimationKey.Shoot],
          [AnimationKey.SitDown]: result.animationGroups[AnimationKey.SitDown],
          [AnimationKey.StandUp]: result.animationGroups[AnimationKey.StandUp],
          [AnimationKey.Victory]: result.animationGroups[AnimationKey.Victory],
          [AnimationKey.Walk]: result.animationGroups[AnimationKey.Walk],
          [AnimationKey.WalkCarry]: result.animationGroups[AnimationKey.WalkCarry],
        });

        result.addAllToScene();

        setMeshes(result.meshes);
      });
    }
  }, [props.scene]);

  useEffect(() => {
    if (meshes[0] && props.player) {
      meshes[0].setAbsolutePosition(new BABYLON.Vector3(...props.player.position));
      meshes[0].rotation = new BABYLON.Vector3(...props.player.rotation);

      if (props.player.moveDirection) {
        switchAnimation(currentAnimation, AnimationKey.Walk);
      } else {
        switchAnimation(currentAnimation, AnimationKey.Idle);
      }
    }
  });

  // currentAnimation is a parameter for optimization purpose
  const switchAnimation = useCallback(
    (
      currentAnimation: BABYLON.AnimationGroup | undefined,
      animationKey: AnimationKey,
    ): void => {
      if (animations) {
        const animation = animations[animationKey];

        if (currentAnimation !== animation) {
          currentAnimation?.stop();
          setCurrentAnimation(animation);
          animation?.play(true);
        }
      }
    },
    [animations, setCurrentAnimation],
  );

  const keyboardEventHandler = useCallback(
    ({ type, event }: BABYLON.KeyboardInfo) => {
      if (type === BABYLON.KeyboardEventTypes.KEYDOWN) {
        switch (event.key) {
          case Key.z:
            props.updateMoveDirection(MoveDirection.Forward);
            break;
          case Key.s:
            props.updateMoveDirection(MoveDirection.Backward);
            break;
          case Key.a:
            props.updateMoveDirection(MoveDirection.Left);
            break;
          case Key.e:
            props.updateMoveDirection(MoveDirection.Right);
            break;
          case Key.d:
            props.updateRotationDirection(RotationDirection.Right);
            break;
          case Key.q:
            props.updateRotationDirection(RotationDirection.Left);
            break;
          default:
            break;
        }
      } else {
        if (isMoveDirection(event.key)) {
          props.updateMoveDirection(MoveDirection.None);
        } else if (isRotationDirection(event.key)) {
          props.updateRotationDirection(RotationDirection.None);
        }
      }
    },
    [
      props.scene,
      props.updateMoveDirection,
      props.updateRotationDirection,
      switchAnimation,
    ],
  );

  useEffect(() => {
    if (props.scene) {
      const keyboardEventObserver = props.scene.onKeyboardObservable.add(
        keyboardEventHandler,
      );

      return (): void => {
        props?.scene?.onKeyboardObservable?.remove(keyboardEventObserver);
      };
    }
  }, [keyboardEventHandler]);

  useEffect(() => {
    if (props.camera && meshes[0]) {
      props.camera.lockedTarget = meshes[0];
    }
  }, [props.camera, meshes]);

  return null;
};

export default Player;
