// packages/web/src/components/game/game/game.tsx
import React, { useEffect, useRef, useState } from 'react';
import styles from './game.module.scss';
import { Game as GameModel } from '../../../models';
import { FocusStore } from '../../../stores';
import { FocusElement } from '../../../types';
import { useGame } from '@reapers/game-client';
import { servers } from '../../../configs/servers';

type GameProps = {
  playerName: string;
};

const Game: React.FC<GameProps> = (props) => {
  const canvasEl = useRef<HTMLCanvasElement>(null);
  const { joinGame, player, world } = useGame(servers.game.url);
  const [gameModel, setGameModel] = useState<GameModel>();
  const focusElement = FocusStore.useStoreState((state) => state.focusElement);

  useEffect(() => {
    document.body.style.overflow = 'hidden';
  }, [document]);

  useEffect((): void => {
    joinGame(props.playerName);
  }, [joinGame, props.playerName]);

  useEffect(() => {
    if (canvasEl.current) {
      const gameModel = new GameModel(canvasEl.current);
      setGameModel(gameModel);

      const handleResize = (): void => gameModel.resize();
      window.addEventListener('resize', handleResize);

      return (): void => {
        window.removeEventListener('resize', handleResize);
      };
    }
  }, []);

  useEffect(() => {
    gameModel?.createWorld(world.width, world.depth);
  }, [world]);

  useEffect(() => {
    gameModel?.createPlayer();
  }, [player]);

  useEffect(() => {
    if (focusElement === FocusElement.Game) {
      canvasEl.current?.focus();
    } else {
      canvasEl.current?.blur();
    }
  }, [focusElement]);

  return <canvas className={styles.game} ref={canvasEl} />;
};

export default Game;

// packages/app/src/components/Game/Game.svelte
<script lang="ts">
  import * as BABYLON from '@babylonjs/core';
  import { onMount } from 'svelte';
  import { useGame, game } from '@reapers/game-client';
  import { FocusElement, focusElement, playerName } from '../../stores';
  import { servers } from '../../configs/servers.config';
  import World from '../World/World.svelte';
  import Player from '../Player/Player.svelte';
  import { createCamera, createEngine, createScene } from './game.utils';

  let canvas: HTMLCanvasElement | undefined;
  let engine: BABYLON.Engine | undefined;
  let scene: BABYLON.Scene | undefined;
  let camera: BABYLON.FollowCamera | undefined;

  const { joinGame, leaveGame, updateMoveDirection, updateRotationDirection } = useGame(
    servers.game.url,
  );

  onMount(() => {
    joinGame($playerName);

    engine = createEngine(canvas as HTMLCanvasElement);
    scene = createScene(engine);
    camera = createCamera(scene);
    engine.runRenderLoop(function () {
      scene?.render();
    });

    const handleResize = () => engine?.resize();
    window.addEventListener('resize', handleResize);

    return () => {
      leaveGame();
      window.removeEventListener('resize', handleResize);
    };
  });

  $: {
    if ($focusElement === FocusElement.Game) {
      canvas?.focus();
    } else {
      canvas?.blur();
    }
  }
</script>

<div class="Game">
  <div class="engineInfos">
    {engine?.getFps().toFixed()}
  </div>
  <canvas bind:this={canvas} />
  <World world={$game.world} {scene} />

  {#each $game.players as player}
    <Player {scene} {player} {camera} />
  {/each}
  <!-- {players.map((player) =>
    player.id === activePlayerId ? (
      <ActivePlayer
        frameIndex={frameIndex}
        key={player.id}
        scene={scene}
        player={player}
        updateMoveDirection={updateMoveDirection}
        updateRotationDirection={updateRotationDirection}
        camera={camera}
      />
    ) : (
      <Player frameIndex={frameIndex} key={player.id} scene={scene} player={player} />
    ),
  )} -->
</div>

<style>
  .Game {
    position: absolute;
    z-index: var(--game-z-index);
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  .Game,
  .Game canvas {
    width: 100%;
    height: 100%;
  }

  .engineInfos {
    position: absolute;
    top: 0;
    left: 0;
    padding: 1rem;
    background-color: rgba(var(--color-black-rgb), 0.3);
    color: var(--color-white);
  }
</style>
